# 应用名称
# 应用服务 WEB 访问端口
spring:
  application:
    name:elasticsearch-sample-01

server:
  port: 8080


elasticsearch:
  httpHost: localhost:9200 #多个结点中间用逗号分隔
  connectTimeout: 10000  #http连接超时时间
  socketTimeout: 10000 #socket连接超时时间
  connectionRequestTimeout: 500  #获取连接的超时时间
  maxConnTotal: 100 #最大连接数
  maxConnPerRoute: 100  #最大路由连接数
  executeTimeout: 8 #任务最长可执行时间 (单位:小时)
  username:
  password: